// ============================================================
// apps/web/lib/agents/retry.ts
// ============================================================
// Retry policy implementation for agent nodes.
//
// Exports:
//   withRetry(nodeFn, policy) — wraps a node function with exponential backoff
//   RetryPolicy               — configuration type
//   DEFAULT_RETRY_POLICY      — standard policy used by graph.ts
//
// Per SPEC:
//   - Backoff schedule: [1000, 3000, 8000] ms
//   - Only retries on whitelisted error codes
//   - NEVER retries on validation failures or confidence-below-threshold
// ============================================================

import type { AgentState, AuditWarning, AuditStatus } from "@auditsimple/types";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type NodeFn = (state: AgentState) => Promise<Partial<AgentState>>;

export interface RetryPolicy {
    /** Max number of retry attempts (not counting the original call) */
    maxAttempts: number;
    /** Delay in ms between attempts (index 0 = first retry, index 1 = second, etc.) */
    backoffMs: number[];
    /** Anthropic / fetch error codes that are eligible for retry */
    retryableErrorCodes: string[];
    /**
     * The AuditStatus stage to attach to warning messages generated by this policy.
     * Imported from the node level so we keep retry.ts dependency-free of node imports.
     */
    stage: AuditStatus;
}

// ---------------------------------------------------------------------------
// Whitelisted error codes (per SPEC)
// These represent transient infrastructure failures — NOT logic failures.
// ---------------------------------------------------------------------------

const RETRYABLE_CODES = [
    "overloaded_error",
    "api_error",
    "timeout",
    "rate_limit_error",
    // HTTP status equivalents (Anthropic SDK normalises these)
    "529",
    "500",
    "503",
    "504",
] as const;

// ---------------------------------------------------------------------------
// Default policy
// ---------------------------------------------------------------------------

/**
 * Default retry policy applied to classify and extract_clauses nodes.
 * graph.ts supplies the correct AuditStatus.stage at registration time.
 */
export function buildDefaultPolicy(stage: AuditStatus): RetryPolicy {
    return {
        maxAttempts: 2, // 1 original + 2 retries = 3 total attempts
        backoffMs: [1000, 3000, 8000],
        retryableErrorCodes: [...RETRYABLE_CODES],
        stage,
    };
}

// ---------------------------------------------------------------------------
// Error code extractor
// ---------------------------------------------------------------------------

/**
 * Extracts the error code from various error shapes thrown by the Anthropic SDK
 * or native fetch calls.
 */
function extractErrorCode(err: unknown): string {
    if (err instanceof Error) {
        // Anthropic SDK error: err.status (HTTP status) or err.error?.type
        const anthropicErr = err as Error & {
            status?: number;
            error?: { type?: string };
        };
        if (anthropicErr.error?.type) return anthropicErr.error.type;
        if (anthropicErr.status) return String(anthropicErr.status);
        if (err.name === "AbortError" || err.message.includes("timeout")) {
            return "timeout";
        }
        if (err.message.includes("rate limit") || err.message.includes("429")) {
            return "rate_limit_error";
        }
    }
    return "unknown_error";
}

// ---------------------------------------------------------------------------
// Sleep helper
// ---------------------------------------------------------------------------

function sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

// ---------------------------------------------------------------------------
// withRetry
// ---------------------------------------------------------------------------

/**
 * Wraps a node function with exponential-backoff retry logic.
 *
 * Behaviour:
 * 1. Call nodeFn(state)
 * 2. On success, return result immediately
 * 3. On error, check if the code is in the whitelist:
 *    - Yes and attempts remain → wait backoffMs[attempt], increment counter, retry
 *    - Yes but no attempts remain → return partial state with warning (graceful degradation)
 *    - No → re-throw immediately (not a transient failure — let pipeline handle it)
 *
 * The wrapped function never throws. Non-retryable errors are re-thrown so
 * that the LangGraph conditional edge can route to the `_retry` or `failed` node.
 *
 * @param nodeFn   The original node function
 * @param policy   Retry configuration
 * @param nodeName The string key of the node (used for retryCounters)
 */
export function withRetry(
    nodeFn: NodeFn,
    policy: RetryPolicy,
    nodeName: string,
): NodeFn {
    return async function retryWrapper(state: AgentState): Promise<Partial<AgentState>> {
        const currentAttempt = (state.retryCounters[nodeName] ?? 0);
        let lastError: unknown;

        for (let attempt = currentAttempt; attempt <= policy.maxAttempts; attempt++) {
            try {
                const result = await nodeFn(state);
                // Success — clear retry counter for this node
                return {
                    ...result,
                    retryCounters: { ...state.retryCounters, [nodeName]: 0 },
                };
            } catch (err) {
                lastError = err;
                const code = extractErrorCode(err);
                const isRetryable = policy.retryableErrorCodes.includes(code);

                if (!isRetryable) {
                    // Non-whitelisted error — re-throw immediately so the graph
                    // conditional edge can route to the correct failure path
                    throw err;
                }

                const nextAttempt = attempt + 1;
                if (nextAttempt > policy.maxAttempts) {
                    // Exhausted retries — fall through to graceful degradation below
                    break;
                }

                // Sleep before next attempt
                const delay = policy.backoffMs[attempt] ?? policy.backoffMs[policy.backoffMs.length - 1];
                await sleep(delay);

                // Persist retry counter in case the graph checkpoints between retries
            }
        }

        // All retries exhausted — return partial state with warning
        const warning: AuditWarning = {
            code: `RETRY_EXHAUSTED_${nodeName.toUpperCase()}`,
            message: `Node "${nodeName}" failed after ${policy.maxAttempts} retry attempts: ${lastError instanceof Error ? lastError.message : String(lastError)
                }`,
            recoverable: false,
            stage: policy.stage,
        };

        return {
            errors: [warning],
            retryCounters: { ...state.retryCounters, [nodeName]: policy.maxAttempts + 1 },
        };
    };
}
